version: '3.7'

services:

  master:
    container_name: mysql_master
    user: "1000:50"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./master/conf/:/etc/mysql/conf.d/
      - ./master/log/:/var/log/mysql/
      - ./master/data:/var/lib/mysql
      - ./master/db:/db
      - ./master/script:/script
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'master'
    command: --innodb-use-native-aio=0
    networks:
      - semi-database-network

  slave:
    container_name: mysql_slave
    user: "1000:50"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./slave/conf/:/etc/mysql/conf.d/
      - ./slave/log/:/var/log/mysql/
      - ./slave/data:/var/lib/mysql
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'slave'
    command: --innodb-use-native-aio=0
    networks:
      - semi-database-network

networks:
  semi-database-network:
    driver: bridge
